### ISSUE TITLE
Automatic cloud translation for this (many dozens of languages)

### ISSUE THREAD

**Issue by Wjxfi** [toaq/toadua-android#9]
I would like this to be done for all sites and libraries and everything else so that everyone can learn this language.

This was done at https://apt.izzysoft.de/fdroid/index/apk/app.suhasdissa.foode::

https://github.com/SuhasDissa/Food-E-App/commit/760cdd528abb8da14a7958e63183b39c32d5b784

https://github.com/SuhasDissa/Food-E-App/commit/672532f58b997f898d264f6fe5cae1acabfb7c27

https://github.com/SuhasDissa/Food-E-App/commit/18e6d5fe1002388ceefdde437cd24c90ba909db3

https://github.com/SuhasDissa/Food-E-App/commit/b221a3c12a139831322ae9c8974ed7ba7b4d6672

https://github.com/SuhasDissa/Food-E-App/commit/f7652d7c68d18c5abf35ab4e64c97f44fe4620d8

**Comment by leafpool243** [comment]
Machine translation is not reliable enough. It would likely misunderstand a lot of the definitions.

**Comment by uakci** [comment]
We would need somebody to translate (1) the toadua-android strings (2) the Toaq definitions themselves. As @leafpool243 says, machine translation would mangle the definitions pretty badly (there are also some challenges ahead that are unique to Slavic languages). So this job would have to be done manually – but I don’t know of any actives in our community who are or speak Russian, so your best bet would be to help us translate them yourself. Sorry.

@robintown How would we feel about closing this as out-of-scope?

**Comment by lynn** [comment]
I suggest you use the [DeepL Chrome extension] (https://chrome.google.com/webstore/detail/deepl-translate-reading-w/cofdbpoegempjloogbagkncekinflcnj?utm_source=deeplcom-en&utm_medium=desktop-web&utm_campaign=pageID110-m-hamburger) with the [web interface to Toadua](https://toadua.uakci.pl/#). I don't think expecting the app to integrate with DeepL's API is reasonable. As far as I know, such an integration costs the developer money past a certain amount of characters per month.

**Comment by uakci** [comment]
@Wjxfi, your passionate interest in this feature is highly welcome; for one, a lot of the tooling, infrastructure, and documentation we have now wouldn’t have come to be without passion. With this said, I fear that we can’t turn your suggestions into constructive goals, mainly because as @lynn deftly points out, existing tools can already do this and they do it well. Unless the combination of these existing tools is not good enough or suffers from show-stopping flaws, integrating them *into* the app (and not even just the app but as you proposed, the documentation, the wiki, the everything!) is going to come at a lot of cost in measured personhours and very little benefit measured in end-user satisfaction. I’ll tentatively close this as not planned; if we come to agreement on some more concretely achievable and meritorious plan of action, we can reopen it no problem.
